name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Firebase support versions only
        node-version: [8.x, 10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: lint and test
        run: |
          yarn --frozen-lockfile --ignore-optional
          yarn lint
          yarn test
        env:
          CI: true
